name: fix-php-code-style-issues

on: ["workflow_dispatch", "pull_request", "push"]

permissions:
  contents: write

jobs:
  fix_code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Format PHP Code
        run: composer format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: fix code style
          commit_options: "--no-verify"
